name: Auto Update README

on:
  schedule:
    # Runs automatically every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate README & Auto Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          python3 .github/scripts/generate_readme.py
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "docs: scheduled auto-update README.md and folder structure [skip ci]"
            git push origin main
          else
            echo "No changes to commit"
          fi
